### PR TITLE
Using raw mouse event coordinates for calculating positions

### LINKED ISSUE #30: Margin or another div above component with DragSelection causes coordinates to be off
When either a margin or div is above the component containing the DragSelection component, the top coordinate of the selection box is off by that height. 

To reproduce, just add a `margin-top: 50px` to the container class in the [codesandbox](https://codesandbox.io/s/billowing-lake-rzhid4?file=/src/index.css) and drag, the box top is off by 50px. 

In my code, I had a title that was 60px tall and the component that I had the DragSelection component below it. Whenever I tried dragging, the top was 60px higher than where my cursor was.

### PR DESCRIPTION
**Pull request by dsod**
fixes #30 
Removing the subtraction of `containerRef.getParentBoundingClientRect().left` and `containerRef.getParentBoundingClientRect().top` when calculating coordinates solved #30 for us and seems to support more use-cases than previously.

Perhaps I don't completely understand the purpose of subtracting the `containerRef`'s coordinates, however, I've run the tests which all passes and created a example codesandbox with a similar dom structure as in the linked issue.

https://codesandbox.io/s/small-monad-4opz3s?file=/src/App.tsx

Let me know if you have any feedback.

### CODE REVIEW

**Comment by tomaszczura** [comment]
Thanks for the PR! Unfortunately I see that rectangle position is not correct when I scroll down the page

**Comment by dsod** [comment]
Thanks for reviewing and catching that.
We got the scroll working with this change. I'll take another look at this and let you know what I find.

**Comment by dwilt** [comment]
@dsod any updates here?

**Review by SimonPlace — APPROVED** [review]

**Comment by GabrielModog** [comment]
@SimonPlace can you update this?

**Comment by ndtreviv** [comment]
I'm excited for this. Any timescales for getting it in?

**Comment by dsod** [comment]
The issue turned out to be due to initial scroll position not being accounted for when calculating the selectable elements coordinates (which was only done once on first render, according to the examples). Simply adding the scroll offset to the calculation solved it:
```ts
Array.from(elementsContainerRef.current.children).forEach((item) => {
  const { left, top, width, height } = item.getBoundingClientRect();
  selectableItems.current.push({
    left: left + window.scrollX,
    top: top + window.scrollY,
    width,
    height,
  });
});
```

**Comment by ndtreviv** [comment]
For me, this was about where the box is drawn. It was consistently drawn ~170px above where my mouse is even though there is no page scroll.

I moved `<DragSelection />` a few elements up the DOM tree to solve it.

**Pull request closed without merging**
